### ISSUE TITLE
json not needed in setup.py

### ISSUE THREAD

**Issue by dandavies99** [kbspooner/ThermoPlotter#9]
**To Reproduce**
`pip install -e .` currently gives: 
``` 
ERROR: Could not find a version that satisfies the requirement json (from ThermoPlotter==0.2.0) (from versions: none)
ERROR: No matching distribution found for json (from ThermoPlotter==0.2.0)
```
**Probable solution**
json is a built-in package in Python, so it can be removed from the list of requirements in setup.py.

**Comment by kbspooner** [comment]
Couldn't reproduce, but applied your suggested fix anyway, it seems reasonable. Thanks!
